export const products = [{
        "nombre": "Jordan Air 1 Mid I",
        "precio": 140.00,
        "picture": "jordan1.png",
        "categoria": "zapatillas",
        "envio": "Envio Gratis",
        "talle": "35 36 37 38",
        "promociones": "Conocé las promociones",
        "descripcion": "Como un ícono del básquet que se traslada a las calles y la ciudad Las zapatillas Nike Air Force 1 High 07 Lv8 llegaron para completar tu look con mucho estilo y sofisticación. Hechas en un cuero negro y sobre esta base, el detalle hoop en púrpura que se combina con el logo Swoosh y detalles de la marca en el mismo color. La correa ajustable le agrega un detalle llamativo extra y la mediasuela blanca, completa el calzado a la perfección. Su acolchado dentro, mantiene tus pies contenidos, dándote sensación de confort en todo momento. Unas zapatillas que creías que jamás llegarían a tu vida.",
        "Género": "Hombre",
        "Adecuadopara": "Todo el día",
        "Material": "Cuero sintético",
        "Beneficios": "Amortiguación",
        "Composicion": "Capellada:cuero sintétic/suela:goma",
        "Caña": "Alta",
        "Ajuste": "Con Cordones",
        "Importante": "El peso del calzado puede variar según número solicitado. Los talles corresponden a numeración de Argentina",
        "Garantía": "Contra defecto de fabricación",
        "Tecnología": "Nike Air",
        "Origen": "Importado",
        "Marca": "Nike",
    },
    {
        "nombre": "Jordan Air 1 Mid II",
        "precio": 100.00,
        "picture": "jordan1low.png",
        "categoria": "zapatillas",
        "talle": "35 36 37 38",
        "promociones": "Conocé las promociones",
        "descripcion": "Se fabricaron en Italia y por eso recibieron el sobrenombre de «Itallian Stallion». El gran éxito de las AJ1 eclipsó de alguna forma este segundo modelo.."
    },
    {
        "nombre": "Jordan Air 1 Mid III",
        "precio": 120.00,
        "picture": "jordan3.png",
        "categoria": "zapatillas",
        "talle": "35 36 37 38",
        "promociones": "Conocé las promociones",
        "descripcion": "Llegaron con una campaña publicitaria con el lema «Gotta Be the Shoes». Fueron las primeras en incluir el logo Jumpman y las vimos en la película She’s Gotta Have It de Spike Lee."
    },
    {
        "nombre": "Jordan Air 1 Mid IV",
        "precio": 347.00,
        "picture": "jordan4.png",
        "categoria": "zapatillas",
        "envio": "Envio Gratis",
        "talle": "35 36 37 38",
        "promociones": "Conocé las promociones",
        "descripcion": "“Taking Flight”. Estas AJ4 fueron la prueba definitiva de que las zapatillas de la marca se convertían en iconos del streetwear. Spike Lee las mostró de nuevo en una de sus películas, esta vez en Haz lo que debas (Do the Right Thing)."
    },
    {
        "nombre": "Jordan Air 1 Mid V",
        "precio": 347.00,
        "picture": "jordan5.png",
        "categoria": "zapatillas",
        "talle": "35 36 37 38",
        "promociones": "Conocé las promociones",
        "descripcion": "“The Fighter”. Inspiradas en la forma de jugar de Michael Jordan y en una de sus mejores temporadas."
    },
    {
        "nombre": "Jordan Air 1 Mid VI",
        "precio": 170.00,
        "picture": "jordan6.png",
        "categoria": "zapatillas",
        "talle": "35 36 37 38",
        "promociones": "Conocé las promociones",
        "descripcion": "“Promised Land”. Fueron las zapatillas que llevó durante la victoria del campeonato de la NBA del mismo año."
    },
    {
        "nombre": "Jordan Air 1 Mid VII",
        "precio": 347.00,
        "picture": "jordan7.png",
        "categoria": "zapatillas",
        "envio": "Envio Gratis",
        "talle": "35 36 37 38",
        "promociones": "Conocé las promociones",
        "descripcion": "Apodadas también como “Pure Gold” por el oro conseguido por la selección estadounidense en los Juegos Olímpicos de Barcelona en 1992."
    },
    {
        "nombre": "Jordan Air 1 Mid VIII",
        "precio": 347.00,
        "picture": "jordan8.png",
        "categoria": "zapatillas",
        "talle": "35 36 37 38",
        "promociones": "Conocé las promociones",
        "descripcion": "Las “Strap In” celebraban la tercera victoria consecutiva en la NBA. Uno de los colores más famosos es el Aqua Tone."
    },
    {
        "nombre": "Jordan Air 1 Mid IX",
        "precio": 347.00,
        "picture": "jordan9.png",
        "categoria": "zapatillas",
        "talle": "35 36 37 38",
        "promociones": "Conocé las promociones",
        "descripcion": "“Perfect Harmony”. Estas zapatillas querían rendir homenaje a Jordan tras anunciar su retirada del baloncesto."
    },
    {

        "nombre": "Jordan Air 1 Mid X",
        "precio": 347.00,
        "picture": "jordan10.png",
        "envio": "Envio Gratis",
        "categoria": "zapatillas",
        "talle": "35 36 37 38",
        "promociones": "Conocé las promociones",
        "descripcion": "“The Legacy Continues”. Michael Jordan manda un fax a los Chicago Bulls con el mensaje “I’m back” («He vuelto»)."
    },
    {

        "nombre": "Jordan Air 1 Mid XI",
        "precio": 125.00,
        "picture": "jordan11.png",
        "categoria": "zapatillas",
        "talle": "35 36 37 38",
        "promociones": "Conocé las promociones",
        "descripcion": "“Class Act”. Las AJ11 celebran el retorno de THE GOAT a las canchas de baloncesto."
    },
    {

        "nombre": "AIR-JORDAN XII",
        "precio": 347.00,
        "picture": "jordan12.png",
        "envio": "Envio Gratis",
        "categoria": "zapatillas",
        "talle": "35 36 37 38",
        "promociones": "Conocé las promociones",
        "descripcion": "“The Dynasty Continues”. Es uno de los modelos más resistentes de la colección. Las pudimos ver en el famoso partido apodado «Flu Game»."
    },
    {

        "nombre": "Jordan Air 1 Mid XIII",
        "precio": 347.00,
        "picture": "jordan13.png",
        "categoria": "zapatillas",
        "talle": "35 36 37 38",
        "promociones": "Conocé las promociones",
        "descripcion": "También conocidas como “Black Cat Puonces” por el alias de «Gato negro» que se le daba al jugador por su destreza y habilidad."
    },
    {

        "nombre": "Jordan Air 1 Mid XIV",
        "precio": 347.00,
        "picture": "jordan14.png",
        "categoria": "zapatillas",
        "talle": "35 36 37 38",
        "promociones": "Conocé las promociones",
        "descripcion": "“Race Ready”. Su diseño se inspiró en el Ferrari 550 M de Jordan. Están decoradas con un total de 14 logos Jumpman."
    },
    {

        "nombre": "Jordan Air 1 Mid XV",
        "precio": 347.00,
        "picture": "jordan15.png",
        "categoria": "zapatillas",
        "talle": "35 36 37 38",
        "promociones": "Conocé las promociones",
        "descripcion": "“Speed of Sound”. Es el modelo número 13 que Tinker Hatfield diseñó de forma consecutiva para la colección. Coincidieron con el año de la segunda retirada de Michael Jordan."
    },
    {

        "nombre": "Jordan Air 1 Mid XVI",
        "precio": 347.00,
        "picture": "jordan16.png",
        "envio": "Envio Gratis",
        "categoria": "zapatillas",
        "talle": "35 36 37 38",
        "promociones": "Conocé las promociones",
        "descripcion": "“Marching On”. Diseñadas por Wilson Smith III, iniciaban una nueva etapa en la línea de zapatillas Jordan."
    },
    {

        "nombre": "Remera negra",
        "precio": 60.00,
        "picture": "remera-negra-mujer.png",
        "categoria": "remeras",
        "envio": "Envio Gratis",
        "talle": "XS S M L",
        "promociones": "Conocé las promociones",
        "descripcion": "Como un ícono del básquet que se traslada a las calles y la ciudad Las zapatillas Nike Air Force 1 High 07 Lv8 llegaron para completar tu look con mucho estilo y sofisticación. Hechas en un cuero negro y sobre esta base, el detalle hoop en púrpura que se combina con el logo Swoosh y detalles de la marca en el mismo color. La correa ajustable le agrega un detalle llamativo extra y la mediasuela blanca, completa el calzado a la perfección. Su acolchado dentro, mantiene tus pies contenidos, dándote sensación de confort en todo momento. Unas zapatillas que creías que jamás llegarían a tu vida.",
        "Género": "Mujer",
        "AdecuadoPara": "Todo el día.",
        "Material": "Algodón.",
        "Capucha": "Sin Capucha",
        "Abertura": "Con Cierre",
        "Cuello": "Alto",
        "Estilo": "Liso",
        "Garantía": "Contra defecto de fabricación.",
        "Origen": "Importado",
        "Marca": "Nike",
    },
    {

        "nombre": "Remera Nike Jordan",
        "precio": 60.00,
        "picture": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.modoliso.com.ar%2Fproductos%2Fremera-negra-lisa-puro-algodon%2F&psig=AOvVaw1ZAuk8tt274MizCYKLdXGD&ust=1663798118724000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCMihmJGxpPoCFQAAAAAdAAAAABAI",
        "categoria": "remeras",
        "envio": "Envio Gratis",
        "talle": "XS S M L",
        "promociones": "Conocé las promociones",
        "descripcion": "Como un ícono del básquet que se traslada a las calles y la ciudad Las zapatillas Nike Air Force 1 High 07 Lv8 llegaron para completar tu look con mucho estilo y sofisticación. Hechas en un cuero negro y sobre esta base, el detalle hoop en púrpura que se combina con el logo Swoosh y detalles de la marca en el mismo color. La correa ajustable le agrega un detalle llamativo extra y la mediasuela blanca, completa el calzado a la perfección. Su acolchado dentro, mantiene tus pies contenidos, dándote sensación de confort en todo momento. Unas zapatillas que creías que jamás llegarían a tu vida.",
        "Género": "Mujer",
        "AdecuadoPara": "Todo el día.",
        "Material": "Algodón.",
        "Capucha": "Sin Capucha",
        "Abertura": "Con Cierre",
        "Cuello": "Alto",
        "Estilo": "Liso",
        "Garantía": "Contra defecto de fabricación.",
        "Origen": "Importado",
        "Marca": "Nike",
    },
    {

        "nombre": "Remera Retro",
        "precio": 25.00,
        "picture": "Remera-Retro-mujer.png",
        "categoria": "remeras",
        "envio": "Envio Gratis",
        "talle": "XS S M L",
        "promociones": "Conocé las promociones",
        "descripcion": "Como un ícono del básquet que se traslada a las calles y la ciudad Las zapatillas Nike Air Force 1 High 07 Lv8 llegaron para completar tu look con mucho estilo y sofisticación. Hechas en un cuero negro y sobre esta base, el detalle hoop en púrpura que se combina con el logo Swoosh y detalles de la marca en el mismo color. La correa ajustable le agrega un detalle llamativo extra y la mediasuela blanca, completa el calzado a la perfección. Su acolchado dentro, mantiene tus pies contenidos, dándote sensación de confort en todo momento. Unas zapatillas que creías que jamás llegarían a tu vida.",
        "Género": "Mujer",
        "AdecuadoPara": "Todo el día.",
        "Material": "Algodón.",
        "Cuello": "Redondo",
        "Estilo": "Estampado",
        "Garantía": "Contra defecto de fabricación.",
        "Origen": "Importado",
        "Marca": "Jordan",
    },
    {

        "nombre": "Remera Nike Sportswear ",
        "precio": 22.00,
        "picture": "remera-rosa-mujer.png",
        "categoria": "remeras",
        "envio": "Envio Gratis",
        "talle": "XS S M L",
        "promociones": "Conocé las promociones",
        "descripcion": "Como un ícono del básquet que se traslada a las calles y la ciudad Las zapatillas Nike Air Force 1 High 07 Lv8 llegaron para completar tu look con mucho estilo y sofisticación. Hechas en un cuero negro y sobre esta base, el detalle hoop en púrpura que se combina con el logo Swoosh y detalles de la marca en el mismo color. La correa ajustable le agrega un detalle llamativo extra y la mediasuela blanca, completa el calzado a la perfección. Su acolchado dentro, mantiene tus pies contenidos, dándote sensación de confort en todo momento. Unas zapatillas que creías que jamás llegarían a tu vida.",
        "Género": "Mujer",
        "AdecuadoPara": "Todo el día.",
        "Material": "Algodón.",
        "Cuello": "Redondo",
        "Estilo": "Estampado",
        "Garantía": "Contra defecto de fabricación.",
        "Origen": "Importado",
        "Marca": "Nike",
    },
    {

        "nombre": "Remera Nike Short Sleeve",
        "precio": 22.00,
        "picture": "remera-corta.png",
        "categoria": "remeras",
        "envio": "Envio Gratis",
        "talle": "XS S M L",
        "promociones": "Conocé las promociones",
        "descripcion": "Como un ícono del básquet que se traslada a las calles y la ciudad Las zapatillas Nike Air Force 1 High 07 Lv8 llegaron para completar tu look con mucho estilo y sofisticación. Hechas en un cuero negro y sobre esta base, el detalle hoop en púrpura que se combina con el logo Swoosh y detalles de la marca en el mismo color. La correa ajustable le agrega un detalle llamativo extra y la mediasuela blanca, completa el calzado a la perfección. Su acolchado dentro, mantiene tus pies contenidos, dándote sensación de confort en todo momento. Unas zapatillas que creías que jamás llegarían a tu vida.",
        "Género": "Mujer",
        "AdecuadoPara": "Todo el día.",
        "Material": "Algodón.",
        "Cuello": "Redondo",
        "Estilo": "Estampado",
        "Garantía": "Contra defecto de fabricación.",
        "Origen": "Importado",
        "Marca": "Nike",
    },
    {

        "nombre": "Pantalón Nike Sportswear ",
        "precio": 87.00,
        "picture": "Pantalón-Nike-Sportswear-mujer.png",
        "categoria": "pantalones",
        "envio": "Envio Gratis",
        "talle": "XS S M L",
        "promociones": "Conocé las promociones",
        "descripcion": "Como un ícono del básquet que se traslada a las calles y la ciudad Las zapatillas Nike Air Force 1 High 07 Lv8 llegaron para completar tu look con mucho estilo y sofisticación. Hechas en un cuero negro y sobre esta base, el detalle hoop en púrpura que se combina con el logo Swoosh y detalles de la marca en el mismo color. La correa ajustable le agrega un detalle llamativo extra y la mediasuela blanca, completa el calzado a la perfección. Su acolchado dentro, mantiene tus pies contenidos, dándote sensación de confort en todo momento. Unas zapatillas que creías que jamás llegarían a tu vida.",
        "Género": "Mujer",
        "AdecuadoPara": "Todo el día.",
        "Material": "Poliéster.",
        "Bolsillo": "Con Bolsillo",
        "Estilo": "Estampado",
        "Cintura": "Con Elástico y Cordón",
        "Garantía": "Contra defecto de fabricación.",
        "Origen": "Importado",
        "Marca": "Nike",
    },
    {

        "nombre": "Pantalón Nike Sportswear ",
        "precio": 85.00,
        "picture": "Pantalón-Nike-Sportswear-Icon-Clash.png",
        "categoria": "pantalones",
        "envio": "Envio Gratis",
        "talle": "XS S M L",
        "promociones": "Conocé las promociones",
        "descripcion": "Como un ícono del básquet que se traslada a las calles y la ciudad Las zapatillas Nike Air Force 1 High 07 Lv8 llegaron para completar tu look con mucho estilo y sofisticación. Hechas en un cuero negro y sobre esta base, el detalle hoop en púrpura que se combina con el logo Swoosh y detalles de la marca en el mismo color. La correa ajustable le agrega un detalle llamativo extra y la mediasuela blanca, completa el calzado a la perfección. Su acolchado dentro, mantiene tus pies contenidos, dándote sensación de confort en todo momento. Unas zapatillas que creías que jamás llegarían a tu vida.",
        "Género": "Mujer",
        "AdecuadoPara": "Todo el día.",
        "Material": "Poliéster.",
        "Bolsillo": "Con Bolsillo",
        "Estilo": "Estampado",
        "Cintura": "Con Elástico y Cordón",
        "Garantía": "Contra defecto de fabricación.",
        "Origen": "Importado",
        "Marca": "Nike",
    },
    {

        "nombre": "Pantalon Nike Flow  ",
        "precio": 85.00,
        "picture": "Pantalon-Nike-Flow-mujer.png",
        "categoria": "pantalones",
        "envio": "Envio Gratis",
        "talle": "XS S M L",
        "promociones": "Conocé las promociones",
        "descripcion": "Como un ícono del básquet que se traslada a las calles y la ciudad Las zapatillas Nike Air Force 1 High 07 Lv8 llegaron para completar tu look con mucho estilo y sofisticación. Hechas en un cuero negro y sobre esta base, el detalle hoop en púrpura que se combina con el logo Swoosh y detalles de la marca en el mismo color. La correa ajustable le agrega un detalle llamativo extra y la mediasuela blanca, completa el calzado a la perfección. Su acolchado dentro, mantiene tus pies contenidos, dándote sensación de confort en todo momento. Unas zapatillas que creías que jamás llegarían a tu vida.",
        "Género": "Mujer",
        "AdecuadoPara": "Todo el día.",
        "Material": "Poliéster.",
        "Bolsillo": "Con Bolsillo",
        "Estilo": "Estampado",
        "Cintura": "Con Elástico y Cordón",
        "Garantía": "Contra defecto de fabricación.",
        "Origen": "Importado",
        "Marca": "Nike",
    },
    {

        "nombre": "Campera Nike Sportswear",
        "precio": 98.00,
        "picture": "Campera-Nike-Sportswear-mujer.png",
        "categoria": "camperas",
        "envio": "Envio Gratis",
        "talle": "XS S M L",
        "promociones": "Conocé las promociones",
        "descripcion": "Como un ícono del básquet que se traslada a las calles y la ciudad Las zapatillas Nike Air Force 1 High 07 Lv8 llegaron para completar tu look con mucho estilo y sofisticación. Hechas en un cuero negro y sobre esta base, el detalle hoop en púrpura que se combina con el logo Swoosh y detalles de la marca en el mismo color. La correa ajustable le agrega un detalle llamativo extra y la mediasuela blanca, completa el calzado a la perfección. Su acolchado dentro, mantiene tus pies contenidos, dándote sensación de confort en todo momento. Unas zapatillas que creías que jamás llegarían a tu vida.",
        "Género": "Mujer",
        "AdecuadoPara": "Todo el día.",
        "Material": "Algodón.",
        "Capucha": "Sin Capucha",
        "Cuello": "Alto",
        "Bolsillo": "Sin Bolsillo",
        "Estilo": "Estampado",
        "Garantía": "Contra defecto de fabricación.",
        "Origen": "Importado",
        "Marca": "Nike",
    },
    {

        "nombre": "Campera Nike Air Hoodie",
        "precio": 98.00,
        "picture": "Campera-Nike-Air-mujer.png",
        "categoria": "camperas",
        "envio": "Envio Gratis",
        "talle": "XS S M L",
        "promociones": "Conocé las promociones",
        "descripcion": "Como un ícono del básquet que se traslada a las calles y la ciudad Las zapatillas Nike Air Force 1 High 07 Lv8 llegaron para completar tu look con mucho estilo y sofisticación. Hechas en un cuero negro y sobre esta base, el detalle hoop en púrpura que se combina con el logo Swoosh y detalles de la marca en el mismo color. La correa ajustable le agrega un detalle llamativo extra y la mediasuela blanca, completa el calzado a la perfección. Su acolchado dentro, mantiene tus pies contenidos, dándote sensación de confort en todo momento. Unas zapatillas que creías que jamás llegarían a tu vida.",
        "Género": "Mujer",
        "AdecuadoPara": "Todo el día.",
        "Material": "Algodón.",
        "Capucha": "Sin Capucha",
        "Cuello": "Alto",
        "Bolsillo": "Sin Bolsillo",
        "Estilo": "Estampado",
        "Garantía": "Contra defecto de fabricación.",
        "Origen": "Importado",
        "Marca": "Nike",
    },
    {

        "nombre": "Campera Jordan Essentials ",
        "precio": 98.00,
        "picture": "Campera-Jordan-Essentials-Woven.png",
        "categoria": "camperas",
        "envio": "Envio Gratis",
        "talle": "XS S M L",
        "promociones": "Conocé las promociones",
        "descripcion": "Como un ícono del básquet que se traslada a las calles y la ciudad Las zapatillas Nike Air Force 1 High 07 Lv8 llegaron para completar tu look con mucho estilo y sofisticación. Hechas en un cuero negro y sobre esta base, el detalle hoop en púrpura que se combina con el logo Swoosh y detalles de la marca en el mismo color. La correa ajustable le agrega un detalle llamativo extra y la mediasuela blanca, completa el calzado a la perfección. Su acolchado dentro, mantiene tus pies contenidos, dándote sensación de confort en todo momento. Unas zapatillas que creías que jamás llegarían a tu vida.",
        "Género": "Mujer",
        "AdecuadoPara": "Todo el día.",
        "Material": "Algodón.",
        "Capucha": "Sin Capucha",
        "Cuello": "Alto",
        "Bolsillo": "Sin Bolsillo",
        "Estilo": "Estampado",
        "Garantía": "Contra defecto de fabricación.",
        "Origen": "Importado",
        "Marca": "Jordan",
    },
    {

        "nombre": "Buzo Nike Sportswear",
        "precio": 96.00,
        "picture": "Buzo-Nike-Sportswear-Icon-mujer.png",
        "categoria": "buzos",
        "envio": "Envio Gratis",
        "talle": "XS S M L",
        "promociones": "Conocé las promociones",
        "descripcion": "Como un ícono del básquet que se traslada a las calles y la ciudad Las zapatillas Nike Air Force 1 High 07 Lv8 llegaron para completar tu look con mucho estilo y sofisticación. Hechas en un cuero negro y sobre esta base, el detalle hoop en púrpura que se combina con el logo Swoosh y detalles de la marca en el mismo color. La correa ajustable le agrega un detalle llamativo extra y la mediasuela blanca, completa el calzado a la perfección. Su acolchado dentro, mantiene tus pies contenidos, dándote sensación de confort en todo momento. Unas zapatillas que creías que jamás llegarían a tu vida.",
        "Género": "Mujer",
        "AdecuadoPara": "Todo el día.",
        "Material": "Algodón.",
        "Capucha": "Sin Capucha",
        "Abertura": "Con Cierre",
        "Cuello": "Alto",
        "Garantía": "Contra defecto de fabricación.",
        "Origen": "Importado",
        "Marca": "Jordan",
    },
    {

        "nombre": "Buzo Nike Sportswear",
        "precio": 100.00,
        "picture": "Buzo-Nike-Sportswear-mujer.png",
        "categoria": "buzos",
        "envio": "Envio Gratis",
        "talle": "XS S M L",
        "promociones": "Conocé las promociones",
        "descripcion": "Como un ícono del básquet que se traslada a las calles y la ciudad Las zapatillas Nike Air Force 1 High 07 Lv8 llegaron para completar tu look con mucho estilo y sofisticación. Hechas en un cuero negro y sobre esta base, el detalle hoop en púrpura que se combina con el logo Swoosh y detalles de la marca en el mismo color. La correa ajustable le agrega un detalle llamativo extra y la mediasuela blanca, completa el calzado a la perfección. Su acolchado dentro, mantiene tus pies contenidos, dándote sensación de confort en todo momento. Unas zapatillas que creías que jamás llegarían a tu vida.",
        "Género": "Mujer",
        "AdecuadoPara": "Todo el día.",
        "Material": "Algodón.",
        "Capucha": "Sin Capucha",
        "Abertura": "Con Cierre",
        "Cuello": "Alto",
        "Garantía": "Contra defecto de fabricación.",
        "Origen": "Importado",
        "Marca": "Jordan",
    },
    {

        "nombre": "Buzo Nike Sportswear Icon Clash",
        "precio": 105.00,
        "picture": "Buzo-Nike-Sportswear-negro-mujer.png",
        "categoria": "buzos",
        "envio": "Envio Gratis",
        "talle": "XS S M L",
        "promociones": "Conocé las promociones",
        "descripcion": "Como un ícono del básquet que se traslada a las calles y la ciudad Las zapatillas Nike Air Force 1 High 07 Lv8 llegaron para completar tu look con mucho estilo y sofisticación. Hechas en un cuero negro y sobre esta base, el detalle hoop en púrpura que se combina con el logo Swoosh y detalles de la marca en el mismo color. La correa ajustable le agrega un detalle llamativo extra y la mediasuela blanca, completa el calzado a la perfección. Su acolchado dentro, mantiene tus pies contenidos, dándote sensación de confort en todo momento. Unas zapatillas que creías que jamás llegarían a tu vida.",
        "Género": "Mujer",
        "AdecuadoPara": "Todo el día.",
        "Material": "Algodón.",
        "Capucha": "Sin Capucha",
        "Abertura": "Con Cierre",
        "Cuello": "Alto",
        "Garantía": "Contra defecto de fabricación.",
        "Origen": "Importado",
        "Marca": "Jordan",
    },








];



export default products